apiVersion: apps/v1
kind: Deployment
metadata:
  name: tschatclient
spec:
  selector:
    matchLabels:
      app: tschatclient
  template:
    metadata:
      labels:
        app: tschatclient
    spec:
      imagePullSecrets:
        - name: localdockersecrets
      containers:
      - name: tschatclient
        image: registry.fprog.club/tschatclient:{{ tag }}
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tschatclient
spec:
  selector:
    app: tschatclient
  ports:
  - port: 8023
    targetPort: 8080
